# Generated by Django 2.2.12 on 2021-06-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0014_auto_20201026_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='puppet.Environment'),
        ),
    ]
